[tool.poetry]
name = "lottery"
version = "0.3.0"
description = ""
authors = ["Nicolas Voisin <voisin.nicolas@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
pandas = "^1.4.1"
ipykernel = "^6.9.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
ipykernel = "^6.0.3"

[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
